dialogues = [
    ["Your first machine! Exciting, right?", "Probably not.", "Anyway, we first have to familiarize ourselves| by building something simple.", "Build a machine that returns the input as output."],
    ["Machines need to be useful now!", "Increase every input by one and then output it."],
    ["A recent survey taken by the Numberland residents| had interesting results.", "The Number 6 has stated that she is 'afraid' of our| machines!", "Fear is intolerable and punishable by death.", "If the input is 6, return undefined.| Otherwise return the input itself."],
    ["On his way to work today, the manager was| suddenly assaulted by a giant pop-tart.", "The pop-tart followed him to the hospital and then| attacked him again while he was sleeping.", "The unlucky numbers have cursed him, he said.", "We must build a machine to convert these numbers| into lucky ones.", "If the input is 13, output 42. If it is 666,| output 642."],
    ["For some reason, we now have to make a machine| about prime numbers.", "Don't ask questions.", "If the input is prime, output 999."],
    ["Our machines are successful!", "Now we have to mass produce several of them efficiently.", "To do that, we need measurements...", "And to get those we need another machine.", "Output the volume of a cube machine with a side length| equal to the input."],
    ["Each day, our company makes twice as much money| as the day before.", "The first day, we made $40.", "Output the amount of total money made if the| amount of days passed is the input."],
    ["Only knowing the volume of the machine is not enough.", "For more accurrate machines, we need to account| for area.", "Output the surface area of a cube with a volume of the input."],
    ["A tragic event has occured in Numberland.", "We now know why exactly 6 was so scared...", "Last Tuesday, the number 7 ate 9.", "Shock and sadness has overcome all the numbers.", "Negativity is terrible for productivity.", "Output what the input is, but first remove the negative| sign if there is one."],
    ["To celebrate out success, we are hosting| a social event for the numbers!", "All numbers are invited... except zero, since| zero is worth nothing.", "We need a machine to allow the guests inside.", "If the input is 0, output 0. Otherwise, output 1."],
    ["The F.E.L.I.X. machine is faulty.", "On the manager's way to the event this morning, he| slipped on a banana peel and got 27 concussions.", "Make sure to confirm that F.E.L.I.X. outputs| are actually lucky.", "If the input is 42 or 642, output 1.| Otherwise, output 0."],
    ["It turns out zero is not worth nothing.", "All small numbers are!", "None of the miserable tiny numbers should be allowed| to the event either.", "This time, if the input is less than 50, output 0.| Otherwise output 1."],
    ["We just discovered a new type of number!", "Fascinating though they are, these 'decimals' are| quite useless.", "If the input is an integer, return 1. Otherwise return 0."],
    ["An inspector is coming to visit the building on Monday.", "These messy decimals are not a good look.", "Polish them up, why don't you?", "Output the cieling of the input."],
    ["The inspector also checks the numbers' fashion.", "The latest trend is to wear a zero at the units digit.", "If the input's last digit is 0, output the number itself.| Otherwise output 0."],
    ["Some numbers still need to adopt this style.", "We need a machine to tell the numbers how to dress.", "Ouput the least positive amount that can be added to| the input to make it end in two zeroes."],
    ["The building is too crowded!", "The numbers have grown to insane sizes and can no| longer properly fit.", "We will reduce numbers by representing them a| different way.", "Take the sum of a number's digits, then the sum of the digits| of that sum, and so on until a one digit number remains.", "Output this representation of the input."],
    ["Now all we need is to show our mathematical expertise.", "We are currently on the road to proving the Collatz| conjecture!", "If the input is even, output x/2. If it is odd, output 3x+1."],
    ["What is the probability that you are reading this?", "Prediciting the future requires probabilities.", "And probabilities require certain math operators...", "Like factorials.", "Output the factorial of the input."],
    ["The Shortener is making numbers too small.", "This time, output the sum of the digits of the number once."],
    ["The decimals are back again!", "If we can't round them, just convert them to fractions.", "Output the sum of the numerator and denominator| of the fraction form of the input."],
    ["We can predict the future now...", "But the manager wasn't attacked by| pop tarts and bananas in the future.", "We have to reverse time, too.", "To do that, we must first reverse numbers.", "Output the reverse of the input."],
    ["We can now control numbers, power, and time.", "That means we can make...", "Computers.", "We have discovered an ancient computer language| called 'binary.'", "Output the sum of the digits of the binary form| of the input."],
    ["Machines like this are now useless.", "Computers will revolutionize the world.", "It is time to destroy these machines.", "Set the machine on an endless function forever."]
]

dialogues = [
    ["Your first machine! Exciting, right?", "Probably not.", "Anyway, we first have to familiarize ourselves| by building something simple.", "Build a machine that returns the input as output."],
    ["Machines need to be useful now!", "Increase every input by one and then output it."],
    ["A recent survey taken by the Numberland residents| had interesting results.", "The Number 6 has stated that she is 'afraid' of our| machines!", "Fear is intolerable and punishable by death.", "If the input is 6, return undefined.| Otherwise return the input itself."],
    ["We must now build a machine to convert unlucky numbers| into lucky ones.", "If the input is 13, output 42. If it is 666,| output 642."],
    ["For some reason, we now have to make a machine| about prime numbers.", "Don't ask questions.", "If the input is prime, output 999."],
    ["Our machines are successful!", "Now we have to mass produce several of them efficiently.", "To do that, we need measurements...", "And to get those we need another machine.", "Output the volume of a cube machine with a side length| equal to the input."],
    ["Each day, our company makes twice as much money| as the day before.", "The first day, we made $40.", "Output the amount of total money made if the| amount of days passed is the input."],
    ["Only knowing the volume of the machine is not enough.", "For more accurrate machines, we need to account| for area.", "Output the surface area of a cube with a volume of the input."],
    ["A tragic event has occured in Numberland.", "We now know why exactly 6 was so scared...", "Last Tuesday, the number 7 ate 9.", "Shock and sadness has overcome all the numbers.", "Negativity is terrible for productivity.", "Output what the input is, but first remove the negative| sign if there is one."],
    ["To celebrate out success, we are hosting| a social event for the numbers!", "All numbers are invited... except zero, since| zero is worth nothing.", "We need a machine to allow the guests inside.", "If the input is 0, output 0. Otherwise, output 1."],
    ["The F.E.L.I.X. machine is faulty.", "On the manager's way to the event this morning, he| slipped on a banana peel and got 27 concussions.", "Make sure to confirm that F.E.L.I.X. outputs| are actually lucky.", "If the input is 42 or 642, output 1.| Otherwise, output 0."],
    ["It turns out zero is not worth nothing.", "All small numbers are!", "None of the miserable tiny numbers should be allowed| to the event either.", "This time, if the input is less than 50, output 0.| Otherwise output 1."],
    ["We just discovered a new type of number!", "Fascinating though they are, these 'decimals' are| quite useless.", "If the input is an integer, return 1. Otherwise return 0."],
    ["An inspector is coming to visit the building on Monday.", "These messy decimals are not a good look.", "Polish them up, why don't you?", "Output the cieling of the input."],
    ["The inspector also checks the numbers' fashion.", "The latest trend is to wear a zero at the units digit.", "If the input's last digit is 0, output the number itself.| Otherwise output 0."],
    ["Some numbers still need to adopt this style.", "We need a machine to tell the numbers how to dress.", "Ouput the least positive amount that can be added to| the input to make it end in two zeroes."],
    ["The building is too crowded!", "The numbers have grown to insane sizes and can no| longer properly fit.", "We will reduce numbers by representing them a| different way.", "Take the sum of a number's digits, then the sum of the digits| of that sum, and so on until a one digit number remains.", "Output this representation of the input."],
    ["Now all we need is to show our mathematical expertise.", "We are currently on the road to proving the Collatz| conjecture!", "If the input is even, output x/2. If it is odd, output 3x+1."],
    ["What is the probability that you are reading this?", "Prediciting the future requires probabilities.", "And probabilities require certain math operators...", "Like factorials.", "Output the factorial of the input."],
    ["The Shortener is making numbers too small.", "This time, output the sum of the digits of the number once."],
    ["The decimals are back again!", "If we can't round them, just convert them to fractions.", "Output the sum of the numerator and denominator| of the fraction form of the input."],
    ["We can predict the future now...", "But the manager wasn't attacked by| pop tarts and bananas in the future.", "We have to reverse time, too.", "To do that, we must first reverse numbers.", "Output the reverse of the input."],
    ["We can now control numbers, power, and time.", "That means we can make...", "Computers.", "We have discovered an ancient computer language| called 'binary.'", "Output the sum of the digits of the binary form| of the input."],
    ["Machines like this are now useless.", "Computers will revolutionize the world.", "It is time to destroy these machines.", "Set the machine on an endless function forever."]
]

