flagnames = [
    "Andorra", "United Arab Emirates", "Afghanistan", "Antigua and Barbuda",
    "Albania", "Armenia", "Angola", "Argentina", "Austria", "Australia", "Azerbaijan",
    "Bosnia and Herzegovina", "Barbados", "Bangladesh", "Belgium", "Burkina Faso",
    "Bulgaria", "Bahrain", "Burundi", "Benin", "Bolivia", "Brazil", "Bahamas",
    "Bhutan", "Botswana", "Belarus", "Belize", "Canada", "Democratic Republic of the Congo",
    "Central African Republic", "Republic of the Congo", "Switzerland", "Ivory Coast",
    "Chile", "Cameroon", "China", "Colombia", "Costa Rica", "Cuba", "Cape Verde",
    "Cyprus", "Czech Republic", "Germany", "Djibouti", "Denmark", "Dominica",
    "Dominican Republic", "Algeria", "Ecuador", "Estonia", "Egypt", "Eritrea",
    "Spain", "Ethiopia", "Finland", "Fiji", "France", "Gabon", "United Kingdom",
    "Grenada", "Georgia", "Ghana", "Gambia", "Guinea", "Equatorial Guinea", "Greece",
    "Guatemala", "Guinea-Bissau", "Guyana", "Honduras", "Croatia", "Haiti", "Hungary",
    "Indonesia", "Ireland", "Israel", "India", "Iraq", "Iran", "Iceland", "Italy",
    "Jamaica", "Jordan", "Japan", "Kenya", "Kyrgyzstan", "Cambodia", "Kiribati",
    "Comoros", "Saint Kitts and Nevis", "North Korea", "South Korea", "Kuwait",
    "Kazakhstan", "Laos", "Lebanon", "Saint Lucia", "Liechtenstein", "Sri Lanka",
    "Liberia", "Lesotho", "Lithuania", "Luxembourg", "Latvia", "Libya", "Morocco",
    "Monaco", "Moldova", "Montenegro", "Madagascar", "Marshall Islands",
    "North Macedonia", "Mali", "Myanmar", "Mongolia", "Mauritania", "Malta",
    "Mauritius", "Maldives", "Malawi", "Mexico", "Malaysia", "Mozambique", "Namibia",
    "Niger", "Nigeria", "Nicaragua", "Netherlands", "Norway", "Nepal", "Nauru",
    "New Zealand", "Oman", "Panama", "Peru", "Papua New Guinea", "Philippines",
    "Pakistan", "Poland", "Portugal", "Palau", "Paraguay", "Qatar", "Romania",
    "Serbia", "Russia", "Rwanda", "Saudi Arabia", "Solomon Islands", "Seychelles",
    "Sudan", "Sweden", "Singapore", "Slovenia", "Slovakia", "Sierra Leone", "San Marino",
    "Senegal", "Somalia", "Suriname", "South Sudan", "Sao Tome and Principe",
    "El Salvador", "Syria", "Eswatini", "Chad", "Togo", "Thailand", "Tajikistan",
    "Timor-Leste", "Turkmenistan", "Tunisia", "Tonga", "Turkey", "Trinidad and Tobago",
    "Tuvalu", "Tanzania", "Ukraine", "Uganda", "United States", "Uruguay", "Uzbekistan",
    "Vatican City", "Saint Vincent and the Grenadines", "Venezuela", "Vietnam",
    "Vanuatu", "Samoa", "Yemen", "South Africa", "Zambia", "Zimbabwe"
]
